name: event_bus_starter
description: A new Flutter projects.
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.8.1
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter

  add:
    path: ../../packages/add

  setting:
    path: ../../packages/setting

  flutter_modular: 6.3.3

flutter:
  uses-material-design: true