name: event_bus_final
description: A new Flutter projects.
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.2.6
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter

  add:
    path: ../../packages/add

  setting:
    path: ../../packages/setting

  flutter_modular: 6.3.3
  event_bus: 2.0.0

flutter:
  uses-material-design: true